### ISSUE TITLE
About Iterative Data Cleaning

### ISSUE THREAD

**Issue by ckx506772099** [JiaxinZhuang/Large-scale-Product-Recognition#1]
Hello, I have read your solution and found the Iterative Data Cleaning in it very interesting. However, because of its simple description, I am confused about how to implement it and how to judge which samples are abandoned. Could you give me some details.

**Comment by JiaxinZhuang** [comment]
Hi, thanks for your interest. Iterative data cleaning is easy to implement, and its aim is to select clean images for training. Steps can be described by 1) All training data forward and get their prediction scores 2) Set the threshold and filter the images to train the model again.

**Comment by ckx506772099** [comment]
Thank you very much for your reply. I have two more questions:
1) What is the threshold set?
2) Is each filtering filtered from all training data or from the training data after the last filtering





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "JiaxinZhuang/Large-scale-Product-Recognition.Pytorch"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月10日(星期三) 下午4:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [JiaxinZhuang/Large-scale-Product-Recognition.Pytorch] About Iterative Data Cleaning (Issue #1)





 
Hi, thanks for your interest. Iterative data cleaning is easy to implement, and its aim is to select clean images for training. Steps can be described by 1) All training data forward and get their prediction scores 2) Set the threshold and filter the images to train the model again.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by JiaxinZhuang** [comment]
1) threshold is a hyper-parameter, for different model, might be different. 
2) filtered from all training data.

**Comment by ckx506772099** [comment]
Thank you for your answer and wish you all the best.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "JiaxinZhuang/Large-scale-Product-Recognition.Pytorch"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月10日(星期三) 晚上7:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [JiaxinZhuang/Large-scale-Product-Recognition.Pytorch] About Iterative Data Cleaning (Issue #1)





  
threshold is a hyper-parameter, for different model, might be different.
 
filtered from all training data.
  
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by JiaxinZhuang** [comment]
Sure. 

> Thank you for your answer and wish you all the best.
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "JiaxinZhuang/Large-scale-Product-Recognition.Pytorch" ***@***.***&gt;; 发送时间:&nbsp;2021年11月10日(星期三) 晚上7:01 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [JiaxinZhuang/Large-scale-Product-Recognition.Pytorch] About Iterative Data Cleaning (Issue #1) threshold is a hyper-parameter, for different model, might be different. filtered from all training data. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.
